#!/usr/bin/env python3
"""Deterministic submission bundler (repo architecture, issue #2).

Copies packages/agent/src/agent into a tar.gz with a generated top-level
main.py, normalizing every source of nondeterminism (mtimes, owners, modes,
entry order, gzip timestamp), and writes the bundle digest to dist/MANIFEST.txt.
tests/test_bundle.py rebuilds and compares — a stale committed bundle fails CI
(the Orbit-Wars generated-submission lesson).
"""

from __future__ import annotations

import gzip
import hashlib
import io
import tarfile
from pathlib import Path

REPO = Path(__file__).resolve().parent
AGENT_SRC = REPO / "packages" / "agent" / "src" / "agent"
DIST = REPO / "dist"

ENTRY = '''"""Kaggle submission entry — generated by build.py; do not edit.

kaggle_environments execs this file WITHOUT __file__ in globals; the agent
directory arrives as config["__raw_path__"] (verified in server PROBE_CONFIG,
issue #15). Resolution is therefore lazy, on first call.
"""

import os
import sys

_inner = None


def _agent_dir(config):
    f = globals().get("__file__")
    if f:
        return os.path.dirname(os.path.abspath(f))
    raw = None
    if config is not None:
        try:
            raw = config.get("__raw_path__")
        except AttributeError:
            raw = None
    if raw:
        return os.path.dirname(os.path.abspath(str(raw)))
    if os.path.isdir("/kaggle_simulations/agent"):
        return "/kaggle_simulations/agent"
    return os.getcwd()


def agent(obs, config=None):
    global _inner
    if _inner is None:
        d = _agent_dir(config)
        if d not in sys.path:
            sys.path.insert(0, d)
        from agent.main import agent as inner
        _inner = inner
    return _inner(obs, config)
'''

EXCLUDE_DIRS = {"__pycache__"}
EXCLUDE_SUFFIXES = {".pyc"}


def _tar_bytes() -> bytes:
    """Build the deterministic tar.gz in memory and return its bytes."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w", format=tarfile.PAX_FORMAT) as tar:

        def add_bytes(name: str, data: bytes, mode: int = 0o644) -> None:
            info = tarfile.TarInfo(name)
            info.size = len(data)
            info.mtime = 0
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            info.mode = mode
            tar.addfile(info, io.BytesIO(data))

        add_bytes("main.py", ENTRY.encode())
        files: list[Path] = []
        for path in sorted(AGENT_SRC.rglob("*")):
            if path.is_dir():
                continue
            if path.suffix in EXCLUDE_SUFFIXES:
                continue
            if any(part in EXCLUDE_DIRS for part in path.relative_to(AGENT_SRC).parts):
                continue
            files.append(path)
        for path in files:
            arcname = "agent/" + path.relative_to(AGENT_SRC).as_posix()
            add_bytes(arcname, path.read_bytes())
    raw = buf.getvalue()

    gz = io.BytesIO()
    with gzip.GzipFile(fileobj=gz, mode="wb", filename="", mtime=0) as f:
        f.write(raw)
    return gz.getvalue()


def build(dist_dir: Path = DIST) -> tuple[Path, str]:
    """Write submission.tar.gz + MANIFEST.txt into ``dist_dir``; return (path, digest)."""
    data = _tar_bytes()
    digest = hashlib.sha256(data).hexdigest()
    dist_dir.mkdir(parents=True, exist_ok=True)
    bundle = dist_dir / "submission.tar.gz"
    bundle.write_bytes(data)
    (dist_dir / "MANIFEST.txt").write_text(f"sha256 {digest}  submission.tar.gz\n")
    return bundle, digest


if __name__ == "__main__":
    bundle_path, sha = build()
    print(f"{bundle_path} sha256={sha}")
